### ISSUE TITLE
"Every millisecond, as long as the stop timeout flag is unset, queue a microtask to run these subsubsubsteps" looks wrong.

### ISSUE THREAD

**Issue by smaug----** [whatwg/xhr#112]
Using microtasks is wrong, and 'every milliseconds' looks suspicious too.

**Comment by annevk** [comment]
So on IRC we discussed an alternative model where setting timeout would simply reset the timer already in process (subtracting the time passed since the fetch started). So if the initial timeout was 500. 100 passed and you set it 200, the timer would run for another 100.

Speaking of timers, @smaug---- thoughts on https://www.w3.org/Bugs/Public/show_bug.cgi?id=28117? It seems preflights and redirects reset the timer in current implementations.

**Comment by annevk** [comment]
@smaug---- I created a pull request for this issue, would appreciate a review. (I already resolved the bug referenced above.)

**Comment by smaug----** [comment]
I guess you mean https://github.com/whatwg/xhr/pull/133 . Looking
