### ISSUE TITLE
final readystatechange (readyState === 3)

### ISSUE THREAD

**Issue by Yaffle** [whatwg/xhr#161]
The specification does not tell to fire the final `readystatechange` event for `readyState === 3`, which is, seems, make the `readystatechange (readyState === 3)`  events not so useful - you have to add `onprogress` listener.

Test case:
A little modified test case for :
https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/event-readystatechange-loaded.htm
But also, check that responseText during readyState === 4 is the same as it was for readyState === 3.

Firefox fail this test. Other browsers do not, seems.

P.S.
not a big deal, you can close this issue if you want.

**Comment by annevk** [comment]
This is defined. Step 11 of https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send. Then under "To process response for response, run these subsubsteps" step 9.4.

**Comment by Yaffle** [comment]
It is, but there is
```
If not roughly 50ms have passed since these subsubsubsteps were last invoked, then terminate these subsubsubsteps. 
```
which allows to exit in some cases... Although Firefox does not fire the event even with 500ms  delays, and the final "progress" is fired

**Comment by annevk** [comment]
That sounds like a bug in Firefox. Would you mind actually creating a test for this and submit a PR against web-platform-tests?

**Comment by Yaffle** [comment]
@annevk, I have created https://github.com/w3c/web-platform-tests/pull/7607 - but :
1) It is not clear what to test;
2) I am a little bit confused by "may be" in the same file. This all looks like an optional thing;

**Comment by Yaffle** [comment]
I was able to reproduce this in Chrome too (if the delay between chunks < 50ms)...
So, it seems, "onprogress" is not the same as "xhr.onreadystatechange = () => if (xhr.readyState === 3) { ... };" - OK.
Sorry for the noise.

**Comment by Yaffle** [comment]
@annevk ,

It seems, the "Comet streaming" is not supported by the specification
There is a page with a code example: https://msdn.microsoft.com/en-us/library/cc304135(v=vs.85).aspx .
It will not work:
1) The spec allows to NOT fire ANY event (progress and readystatechange) in case the second HTTP chunk arrives within 50ms interval since the first.
2) The spec allows to NOT fire the final readystatechange(3) event at all.

By the way, It seems, Firefox and Chrome set the 50ms timer instead of not firing the event as said by: 
```
2. If not roughly 50ms have passed since these subsubsubsteps were last invoked, then terminate these subsubsubsteps.
```

**Comment by annevk** [comment]
I still don't see why you think 2 is true.

**Comment by Yaffle** [comment]
`terminate these subsubsubsteps` will terminate the steps to fire readystatechange(readyState === 3) for the last bytes received

**Comment by annevk** [comment]
`progress` is dispatched from the same set of steps though.

**Comment by Yaffle** [comment]
The final `progress` is dispatched from the steps for https://xhr.spec.whatwg.org/#handle-response-end-of-body

**Comment by annevk** [comment]
Yeah, that's true. I don't think there was a ever a guarantee you would get the full body within `readystatechange` while state is 3 though.

What did you mean by Firefox and Chrome setting the 50ms timer?

**Comment by Yaffle** [comment]
>What did you mean by Firefox and Chrome setting the 50ms timer?
from my *testing*:

When a new data is received within 50 ms interval from the last data the events (progress and readystatechange) are not fired,
but after some amount of milliseconds the events are fired *even* if no new data was received (and the HTTP connection is still not finished).

**Comment by annevk** [comment]
Ah, okay, maybe we should define this differently then.

**Comment by tyoshino** [comment]
Chrome's algorithm is:
- when a new chunk arrives before 50ms passes since the last chunk for that we dispatched a "progress" event, we schedule dispatching of a "progress" event after the 50ms passes.
- when the end of data is signaled with such a scheduled dispatching pending, we flush it to dispatch a "progress" event before dispatching a "readyState" event followed by "load" and "loadend".
- unless there's such a scheduled-but-pending dispatching, we don't fire any "progress" event on the end of data signal, but only "readyState", "load" and "loadend".

Right, this is different from what the spec says.

I remember that we had some discussion before and the following bug is one of them I think. But I don't remember whether we had any further discussion since that.
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26917

We also had some discussion regarding the corner case handling around dispatching of DONE.
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26736

**Comment by wenbozhu** [comment]
> when a new chunk arrives before 50ms passes since the last chunk for that we dispatched a "progress" event, we schedule dispatching of a "progress" event after the 50ms passes.

This is important. I don't think the spec intends to discard throttled events.

Also, does fetch/readablestreams do any similar throttling? If not, I am curious why or how useful it is to spec out such a behavior for xhr.

**Comment by wenbozhu** [comment]
@yutakahirano

**Comment by annevk** [comment]
It's something XHR had historically. I'd be happy to get rid of it. @smaug---- thoughts?

**Comment by smaug----** [comment]
It isn't clear to me what is actually proposed here.

**Comment by annevk** [comment]
I discussed it a bit with @smaug----. There's a worry that removing the throttling might break sites that rely on this timing. E.g., they might end up getting janked if these events suddenly fire more often. If Chrome can prove that is not the case (e.g., by removing throttling and shipping that) Firefox would likely follow though.

**Comment by yutakahirano** [comment]
We had complaints (https://crbug.com/336066) for lack of throttling, so I would like to keep the concept. I would rather update the throttling logic in the spec.

**Comment by wenbozhu** [comment]
(never involved in the spec work) .. but could the throttling behavior be treated as implementation details? I am certain there is hidden throttling in the I/O layer too. It also seems hard for the spec to decide an optimal but fixed throttling interval.  

===

Related, if this is truly useful for the spec to define, then fetch/readable-stream needs be covered too.

**Comment by annevk** [comment]
@wenbozhu well, Fetch/ReadableStream are not bound by the same compatibility issues, so we can avoid this 50ms-based throttling there. Here we decided on it at some point and now sites rely on it to some extent.

**Comment by wenbozhu** [comment]
Possibly, if it is guaranteed that no new data will be dispatched for at least 50ms ... 

Is it possible to just mention the throttling requirement and the (minimum) 50ms rule in the spec, which might actually make the implementations more consistent, as opposed to what we are seeing with Edge/IE's strict implementation of the existing under-specified throttling algorithm?

**Comment by smaug----** [comment]
"If not roughly 50ms have passed since these subsubsubsteps were last invoked, then terminate these subsubsubsteps." is not clear enough?

**Comment by wenbozhu** [comment]
IIUC, this defines the throttling behavior, but what's missing is how to ensure timely and eventual delivery of any buffered "chunks" ... This may require introducing a timer event whenever any data is buffered.

**Comment by yutakahirano** [comment]
Does it make sense to have vague statements, such as

- Let read be the result of reading a chunk from response’s body’s stream with reader.
 - When read is fulfilled with an object whose done property is false and whose value property is a Uint8Array object, run these subsubsubsteps and then run the above subsubstep again:
   1. Append the value property to received bytes.
   1. If state is headers received, then set state to loading and fire an event named readystatechange.
   1. Otherwise, fire an event named readystatechange, but in the following manner:  The user agent may delay or coalesce multiple progress events up to 50ms, as long as [state](https://xhr.spec.whatwg.org/#concept-xmlhttprequest-state) is _loading_.
   1. Fire a progress event named progress with response’s body’s transmitted bytes and response’s body’s total bytes, but in the following manner:  The user agent may delay or coalesce multiple progress events up to 50ms, as long as [state](https://xhr.spec.whatwg.org/#concept-xmlhttprequest-state) is _loading_.

?

**Comment by Mouvedia** [comment]
> but after some amount of milliseconds the events are fired _even_ if no new data was received (and the HTTP connection is still not finished).

Does that mean we could have a redundant progress event fire _after_ the load event was fired? Or does that potentially push back the load event by some ms due to the fact that it has to respect the event order and hence gets delayed by the pending progress event?

**Comment by Yaffle** [comment]
@Mouvedia , no, I think, the browsers delay new events if the data was received within 50 ms interval from the last received data. I didn't test the "load", but it should work as speced (progress is fired (no delay), readystatechange(3) - not).

**Comment by color-infinispace** [comment]
@Yaffle 

Note that there are native web platforms that may not support all the web apis. XHR seems to be the lowest common denominator, still.  Although, I have no idea if developers of those platform follow the whatwg specs for algorithm details like this.

**Comment by annevk** [comment]
My read here is that the status quo is desired. If implementers do want to change the 50ms interval, please file a new issue with some current information.
