### ISSUE TITLE
Should XHR store and send HTTP header names in lower case?

### ISSUE THREAD

**Issue by tzik** [whatwg/xhr#34]
The XHR spec defers HTTP header handling to the Fetch spec, and the header names are byte-lowercased in Fetch spec.
https://xhr.spec.whatwg.org/#the-setrequestheader()-method
https://fetch.spec.whatwg.org/#terminology-headers

However, all major browers don't normalize them at this point. I think this is due to compatibility issue around legacy servers that may handle the header names in case-sensitive manner.
OTOH, I found it's beneficial for Chrome in terms of cleaner code and better performance to normalize all request / response header names to lowercase. 

So, I want to confirm that the XHR is expected to use lowercase header names. Or is that actually expected to pass through the overridden request headers as-is?

**Comment by annevk** [comment]
I think ideally everything is lowercased. Because the exact case will be observable with service workers through the `Headers` API, at least for headers that are set before the network layer. If we cannot make that work with legacy content however we'll need something more complicated. That would be sad.

@wanderview might be interested in this. Maybe @mnot and @jungkees too.

**Comment by mnot** [comment]
HTTP/2 normalises headers to lowercase, and servers (and everyone else) *really* shouldn't be treating them as case-sensitive. Do we have any data about how prevalent this is?

**Comment by tzik** [comment]
I have no data how many servers wrongly treat header names case-sensitively, but I'm a bit pessimistic for it since an embedded web server in the Chrome test infra was case-sensitive.

**Comment by mnot** [comment]
Was that something hand-spun, or a library that's actually used elsewhere?

If it's the first, it seems like poor data to base a decision upon.

**Comment by tzik** [comment]
The first, it's written directly.

Hm, it's probably only to hand-written servers that the lower-cased header names affect to.
Well-established libraries, such as standard libraries of Ruby, Go, NodeJS and Python handle header names case-insensitively, which is correct.
On plain CGI, request headers are passed as HTTP_ environment variable, and the header names are converted to upper case. So, they don't care the case of field names.

**Comment by annevk** [comment]
So this should probably simply follow the resolution of https://github.com/whatwg/fetch/issues/304. I won't close this until that's resolved however.

**Comment by tyoshino** [comment]
I just encountered whatwg/fetch@8114af96a4e02cd3cfb6156795fe45673217f087. It has changed not only the stuff for the Fetch API, but also the `combine` algorithm which was solely used by XHR at that point. Was this intentional or accidental?

**Comment by annevk** [comment]
That was intentional. But the lowercasing of header names will go away per the issue I referenced in my previous commit for both XMLHttpRequest and Fetch. (Though the API in Fetch will only ever expose them as lowercase and we'll continue to use case-insensitive matching to avoid two headers with different casing.)

**Comment by tyoshino** [comment]
Ah, ok. This one https://github.com/whatwg/fetch/issues/304#issuecomment-238870561

Thanks

**Comment by annevk** [comment]
Let me close this in favor of that issue since it's not worth tracking separately.
