### ISSUE TITLE
Status 0 is missing a message

### ISSUE THREAD

**Issue by jtangelder** [whatwg/xhr#35]
It is hard to investigate status 0 errors, since they are [missing a statusText](https://fetch.spec.whatwg.org/#concept-network-error) value. A message would be very helpful, since it can have multiple reasons. (proxy, firewalls, broken cors, empty response...)

**Comment by tyoshino** [comment]
It's for representing the status-code and reason-phrase of the HTTP semantics. If we want to expose something not represented on the status line, we should extend the API surface for it. Embedding such info in the same attributes would be confusing, I think.

At least about CORS, there could be another reason why we don't expose details. It's basically better not to reveal any details about the cross-origin server when it doesn't understand CORS or reject cross-origin access.

For example, Chrome emits a console error explaining what happened. So, developers should be able to investigate it. Do you want to make it visible to script and gather error information (or show the error code to your customers so that they can report detailed info about the error) for debugging?

**Comment by jtangelder** [comment]
Yes, it could be useful for debugging errors on clients. Now it is impossible to find out what caused the request to fail, while the debug tools show a detailed message. It would be nice if the XHR api would contain a property that contains this information for logging purposes.

**Comment by annevk** [comment]
Thus far we refrained from doing that because implementers and security folk were not keen on exposing it. If we'd expose this we wouldn't expose it here, that would break compatibility.

And if we decide this can be done securely, we'd do this as part of `fetch()`, not `XMLHttpRequest`.
