### ISSUE TITLE
Kill the progress event when readyState is 4

### ISSUE THREAD

**Issue by hallvors** [whatwg/xhr#72]
Step 10 in [handle response end of file](https://xhr.spec.whatwg.org/#handle-response-end-of-file) isn't implemented by any web browser and the extra progress event seems somewhat superfluous since several other events can tell you when the request is done. I suggest removing step 10 to align the spec with current implementations.

**Comment by annevk** [comment]
Given f1c744d6cb74371bbbaa4c07f17bfa9e9caa1718 it seems like we should also remove step 4 of "process request end-of-file", and step 6.2 and step 7 of "request error steps", correct?

**Comment by hallvors** [comment]
Not absolutely sure about the implementation state of those steps. Surprisingly, I don't think we even have tests that check this - the error and abort test are more about those specific events. Perhaps just write something ad-hoc?

**Comment by domenic** [comment]
This impacts web platform tests XMLHttpRequest/send-no-response-event-order.htm and XMLHttpRequest/send-sync-response-event-order.htm which currently do not match the spec (and I guess per this do not match implementations either).

**Comment by wisniewskit** [comment]
Having just tested send-response-event-order.htm, send-no-response-event-order.htm, and abort-event-order.htm in Chrome, Firefox, Edge, and a fresh WebKit trunk build, I would recommend these changes:

1. Move "handle response end-of-body" step 10 up so that it is between steps 4 and 5. That is what the browsers are all doing right now: sending their final progress event *before* switching to readyState=4.
2. If it's desired to ensure that progress events' "loaded" values are always greater than (and not equal to) any prior event named progress for the request, then note this in the spec, and change "process response" step 10.4 and "process request body" step 2 to not fire any event if loaded=total (to ensure that we don't potentially repeat sending the "100%" event twice for the upload or download phases). Or if it doesn't matter to the spec whether there are such repeated events, then the tests should be changed so they do not expect only a single event named progress.
3. "process request end-of-body" can remain as-is, since the browsers all fire the progress event as per the spec's current event ordering.
4. Remove the progress events from "handle request error". This is not a decision based on the browser implementations, since there is no consensus among them; Chrome and Edge do not fire them, but WebKit trunk does, and Firefox soon will in version 51, but only because an effort is being made to match the spec right now (see https://bugzilla.mozilla.org/show_bug.cgi?id=918703). As such they might as well just be removed entirely, considering that they don't add any useful information and thus appear to just be wasted effort.
5. Change progress-events-response-data-gzip.htm to remove its check that ProgressEvents will never have loaded=total before readyState=4 (and instead check that the loaded values always increase, if that was the decision that was made in [2]).

**Comment by annevk** [comment]
> If it's desired to ensure that progress events' "loaded" values are always greater than (and not equal to) any prior event named progress for the request, then note this in the spec, and change "process response" step 10.4 and "process request body" step 2 to not fire any event if loaded=total (to ensure that we don't potentially repeat sending the "100%" event twice for the upload or download phases).

This is guaranteed by https://fetch.spec.whatwg.org/#read-a-request as far as I can tell.

**Comment by annevk** [comment]
I will prepare a change to the standard for 1 and 4.

**Comment by wisniewskit** [comment]
>This is guaranteed by https://fetch.spec.whatwg.org/#read-a-request as far as I can tell.

Sure. My concern is just that implementations may not get this right, as Fetch is a relatively new spec and they may not even be using it for their XHR implementations. It might therefore be worth adding notes about this invariant in the XHR spec just to make it clear that's the intent (along with the tests confirming it, just in case). It's minor enough that I'm not going to push for its inclusion, though.

**Comment by annevk** [comment]
I guess I can add a note below "process request body" to indicate it's only invoked when new bytes are available. Does the PR look okay otherwise?

**Comment by wisniewskit** [comment]
Yes, it looks fine to me, thanks.

As long as it's clear enough that the loaded value must never be less than or equal to a previous e.loaded value for the given request, we should be fine (as far as adding a note is concerned).

While we're at it, here's a patch for progress-events-response-data-gzip.htm: http://pastebin.com/51LGvjkR

**Comment by annevk** [comment]
Added a note.

**Comment by KiChjang** [comment]
> If it's desired to ensure that progress events' "loaded" values are always greater than (and not equal to) any prior event named progress for the request, then note this in the spec, and change "process response" step 10.4 and "process request body" step 2 to not fire any event if loaded=total (to ensure that we don't potentially repeat sending the "100%" event twice for the upload or download phases). Or if it doesn't matter to the spec whether there are such repeated events, then the tests should be changed so they do not expect only a single event named progress.

There are actually 2 parts of the spec that this suggestion contains - "process response" and "process request body". Only the latter has been addressed by adding the note. AFAICT the former is not addressed.

**Comment by annevk** [comment]
Can you file a new issue?

**Comment by KiChjang** [comment]
Filed #118.
