### ISSUE TITLE
Property to disable following redirects

### ISSUE THREAD

**Issue by zpul** [whatwg/xhr#74]
This option was considered some time ago:
https://www.w3.org/TR/2008/WD-XMLHttpRequest-20080415/#notcovered

This would be extremely useful to avoid losing response code and headers returned by the original resource.

Best, A.

**Comment by annevk** [comment]
We only add new features to https://github.com/whatwg/fetch. It does have a feature to disable redirects, but it basically turns a redirect into an error. The problem is that we cannot expose the redirect information. Exposing redirect information has to be opt-in so we'd have to add some kind of protocol for that.

Hope that helps.

**Comment by zpul** [comment]
OK thanks. What about having an event `onredirect` that permits to access redirect information and can be used to stop following the redirect itself?

**Comment by annevk** [comment]
That has the same problems, no?
