### ISSUE TITLE
Wrong state after abort()

### ISSUE THREAD

**Issue by tiago** [whatwg/xhr#88]
The `abort()` method, as in the spec:
> 1. Terminate the request.
> 2. If state is either opened with the send() flag set, headers received, or loading, run the request error steps for event abort.
> 3. If state is done, set state to unsent.

Consider this:
```js
var xhr = new XMLHttpRequest(); // UNSENT
xhr.open('GET', '');            // OPENED with send() flag unset
xhr.abort();                    // UNSENT
```

Following the spec, nothing should happen in steps `2` and `3`, leaving the state `OPENED`. This breaks [web-platform-tests/abort-during-open](https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/abort-during-open.js), which expects `UNSENT`.

From what I've seen, `abort()` was last changed in the scope of #54.

At this point I have no good suggestion on how to reformulate it to pass [web-platform-tests/abort-during-open](https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/abort-during-open.js) and [web-platform-tests/open-during-abort](https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/open-during-abort.htm), as both get to step `3` with "OPENED with send() flag unset", but the final status is expected to be different.

**Comment by domenic** [comment]
Do browsers match the test, or the spec?

**Comment by tiago** [comment]
Browsers match the test. Checked with latest Chrome, Firefox, Safari and Edge.

**Comment by berniegp** [comment]
This code snippet from [Chromium's source](https://chromium.googlesource.com/chromium/blink.git/+/refs/heads/master/Source/core/xmlhttprequest/XMLHttpRequest.cpp) spells it out (lines 1002-1038):

```
bool XMLHttpRequest::internalAbort()
{
    m_error = true;
	
    if (m_responseDocumentParser && !m_responseDocumentParser->isStopped())
        m_responseDocumentParser->stopParsing();
		
    clearVariablesForLoading();
	
    if (m_responseLegacyStream && m_state != DONE)
        m_responseLegacyStream->abort();
		
    clearResponse();
    clearRequest();
	
    if (!m_loader)
        return true;
		
    // Cancelling the ThreadableLoader m_loader may result in calling
    // window.onload synchronously. If such an onload handler contains open()
    // call on the same XMLHttpRequest object, reentry happens.
    //
    // If, window.onload contains open() and send(), m_loader will be set to
    // non 0 value. So, we cannot continue the outer open(). In such case,
    // just abort the outer open() by returning false.
    RefPtr<ThreadableLoader> loader = m_loader.release();
    loader->cancel();
	
    // If abort() called internalAbort() and a nested open() ended up
    // clearing the error flag, but didn't send(), make sure the error
    // flag is still set.
    bool newLoadStarted = m_loader;
    if (!newLoadStarted)
        m_error = true;
		
    return !newLoadStarted;
}
```

If `internalAbort()` returns true (i.e. a nested `open()` was done), `abort()` does not set the state to `UNSENT`.

**Comment by annevk** [comment]
@berniegp that does not match what @tiago is reporting for the test.

**Comment by berniegp** [comment]
@annevk: you are right.

I updated my previous comment with more code.

The test [open-during-abort](https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/open-during-abort.htm) *does* set the state to UNSENT in the end. It does not show up in the test however because no `readystatechange` event is fired when setting the state to `UNSENT` in `abort()`. This can be proved by adding a line at the end:

	test(function() {
	var client = new XMLHttpRequest(),
		abort_flag = false,
		result = [],
		expected = [1, 4, 1] // open() => 1, abort() => 4, open() => 1
		
	client.onreadystatechange = this.step_func(function() {
	  result.push(client.readyState)
	  if (abort_flag) {
		abort_flag = false
		client.open("GET", "...")
	  }
	})
	client.open("GET", "resources/well-formed.xml")
	client.send(null)
	abort_flag = true
	client.abort()
	assert_array_equals(result, expected)
	// succeeds in Firefox (as per spec), but fails in Chrome (readyState == UNSENT)
	assert_equals(client.readyState, 1)
	})

Maybe calling `open()` during `abort()` should not be supported, but if it is, the current behavior of Chrome leaves the request in a broken state. The user called `open()` but a subsequent call to `setRequestHeader()` would fail because the state is `UNSENT`.

At the very least, the final `readyState` should be asserted in the test.


As for the other part of this issue, the sequence

1. `xhr.open()`
2. `xhr.abort()`

will set the state to `UNSENT` (not respecting the spec) as the test [abort-during-open](https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/abort-during-open.js) dictates and as the code shows.

**Comment by annevk** [comment]
I tend to think the specification makes more sense here given that invoking `open()` during or before `abort()` doesn't result in a broken state. @wisniewskit @tyoshino are you open to changing Firefox and Chrome here?

**Comment by annevk** [comment]
@cdumez ^^

**Comment by wisniewskit** [comment]
@annevk, I'm game, but changing Firefox to match the spec as it is now *will* cause it to fail the following tests:

-  abort-during-open.htm/worker
-  abort-event-abort.htm
-  send-data-unexpected-tostring.htm (the first test)

The abort-during-open failure is of course already explained in this ticket (the state is never set to "unsent", but stays "open").

The other 2 tests expect send() to throw when following an abort(). However, at the time of abort(), the state is open, but the send flag is *false*, so the request error steps are not called, and the state remains "open, send flag not set" when send() is called, so it never throws the expected InvalidStateError.

(Note that Firefox currently passes the tests because it always changes the state to "unsent" in abort() step 3, not just if it's "done").

**Comment by annevk** [comment]
If everyone else agrees with the change I can update the tests first (unless someone else wants to volunteer).

**Comment by tyoshino** [comment]
Me too fine with fixing our implementation. Thanks for finding this berniegp.

> Maybe calling open() during abort() should not be supported, but if it is, the current behavior of Chrome leaves the request in a broken state. The user called open() but a subsequent call to setRequestHeader() would fail because the state is UNSENT.

Right. When only open() is called in onabort(), we enter UNSENT which is wrong. We'll address this too.

**Comment by wisniewskit** [comment]
So, just to make sure, what are the proposed changes?

**Comment by annevk** [comment]
The proposal is to change the tests.

**Comment by wisniewskit** [comment]
As in, to change the tests I mentioned to expect the XHR state after send()+abort() to be "open, with send() flag unset" instead of "unsent"?

And possibly adding a test (if there isn't one already) to ensure that the state changes to unsent if it was already done when abort() is called (and without a readystatechange event being fired)?

**Comment by annevk** [comment]
Yeah, see https://github.com/w3c/web-platform-tests/pull/4033 for my PR. abort-during-done.htm is the other test you mention.

**Comment by annevk** [comment]
@wisniewskit could you review the PR perhaps?

**Comment by wisniewskit** [comment]
Sure, done.
